<h1>Contact Form</h1>
<?php
/**
 * @var \Dev\Wholesale\Block\Frontend\ContactForm $block
 *
 * param array $customer
 */
$customer = $block->getCurrentCustomer();
?>
<div class="mt-5">
<form action="" method="post" id="custom-form">
        <fieldset class="fieldset">
            <div class="field required">
                <label for="name" class="label"><span><?= $block->escapeHtml(__('Customer Name')) ?></span></label>
                <div class="control">
                    <input type="text" name="name" id="name" class="input-text" data-validate="{required:true}" value="<?php echo $customer->getName() ?>"/>
                </div>
            </div>
            <div class="field required">
                <label for="email" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" name="email" id="email" class="input-email" data-validate="{required:true}" value="<?php echo $customer->getEmail() ?>"/>
                </div>
            </div>
            <div class="field required">
                <label for="phone_number" class="label"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input type="number" name="phone_number" id="phone_number" data-validate="{required:true}" value="0123456678"/>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary actions-primary">
                <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
            </div>
        </div>
    </form>
</div>
