<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Dev\Wholesale\Block\Customer\Wholesale\View $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$product = $block->getProductData();
?>
<?php if ($product->getId()): ?>
<div class="customer-review view">
    <div class="product-details">
        <div class="product-media">
            <a class="product-photo" href="<?= $block->escapeUrl($product->getProductUrl()) ?>">
                <?php /* customer_account_product_review_page */ ?>
                <?= $block->getImage($block->getProductData(), 'customer_account_product_wholesale_page')->toHtml() ?>
            </a>
        </div>
        <div class="product-info">
            <h2 class="product-name"><?= $block->escapeHtml($product->getName()) ?></h2>
        </div>
    </div>

    <div class="review-details">
        <div class="review-content">
            <?= /* @noEscape */ $block->escapeHtml($block->getWholesaleData()->getMessage()) ?>
        </div>
    </div>
</div>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $block->escapeHtml(__('Back to My Products Wholesale')) ?></span>
        </a>
    </div>
</div>
<?php endif; ?>
